// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9rLMlp8tjOsXrseTxZzAze0N4K7GchNA',
    appId: '1:1017137401151:web:20a478a774587500fbd78a',
    messagingSenderId: '1017137401151',
    projectId: 'kite-9ee27',
    authDomain: 'kite-9ee27.firebaseapp.com',
    storageBucket: 'kite-9ee27.firebasestorage.app',
    measurementId: 'G-V9X8V4PEGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu51Q14ZpV97QR3RP8VkK_sTrzHW3qZ0w',
    appId: '1:1017137401151:android:7f23dc7da132244efbd78a',
    messagingSenderId: '1017137401151',
    projectId: 'kite-9ee27',
    storageBucket: 'kite-9ee27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIaORRW0xrVpVk8O0Cfdjuo71ylnpCDco',
    appId: '1:1017137401151:ios:ebb7811f50b78dcefbd78a',
    messagingSenderId: '1017137401151',
    projectId: 'kite-9ee27',
    storageBucket: 'kite-9ee27.firebasestorage.app',
    androidClientId: '1017137401151-84odah1pir9vic2brist7bbcof2egcup.apps.googleusercontent.com',
    iosClientId: '1017137401151-qejm7l5ikk76kotom8cbsvn8kcc9t3nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIaORRW0xrVpVk8O0Cfdjuo71ylnpCDco',
    appId: '1:1017137401151:ios:ebb7811f50b78dcefbd78a',
    messagingSenderId: '1017137401151',
    projectId: 'kite-9ee27',
    storageBucket: 'kite-9ee27.firebasestorage.app',
    androidClientId: '1017137401151-84odah1pir9vic2brist7bbcof2egcup.apps.googleusercontent.com',
    iosClientId: '1017137401151-qejm7l5ikk76kotom8cbsvn8kcc9t3nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9rLMlp8tjOsXrseTxZzAze0N4K7GchNA',
    appId: '1:1017137401151:web:8ddb532e5d900bebfbd78a',
    messagingSenderId: '1017137401151',
    projectId: 'kite-9ee27',
    authDomain: 'kite-9ee27.firebaseapp.com',
    storageBucket: 'kite-9ee27.firebasestorage.app',
    measurementId: 'G-EDZPWHG16T',
  );
}
